[package]
name = "nifty-formatter"
version = "0.1.2"
authors = ["Aster <192607617@qq.com>"]
description = "Nifty formatting: gitmoji subjects, release bullets, and changelog sections"
repository = "https://github.com/oovm/npm-tools"
documentation = "https://docs.rs/nifty-formatter"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
nifty-config = { path = "../nifty-config" }
nifty-types = { path = "../nifty-types" }
oak-typescript = { git = "https://github.com/yggdrasil-language/oaks.git", rev = "d77a25718b1f27af0046475edcde9fd60c90960d" }
serde_json = "1.0"
walkdir = "2.5"

[dev-dependencies]
oak-core = { git = "https://github.com/yggdrasil-language/oaks.git", rev = "d77a25718b1f27af0046475edcde9fd60c90960d" }
oak-javascript = { git = "https://github.com/yggdrasil-language/oaks.git", rev = "d77a25718b1f27af0046475edcde9fd60c90960d" }
oak-testing = { git = "https://github.com/yggdrasil-language/oaks.git", rev = "d77a25718b1f27af0046475edcde9fd60c90960d" }
