[package]
name = "nifty-updater"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "Update cargo and npm dependencies for Nifty hybrid projects"
repository = "https://github.com/oovm/npm-tools"
documentation = "https://docs.rs/nifty-updater"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "nifty"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.11"
nifty-config = { path = "../nifty-config" }
nifty-linter = { path = "../nifty-linter" }
nifty-uploader = { path = "../nifty-uploader" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
