name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish native addon for ${{ matrix.asset_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: nifty-linux-x64-gnu.node
            asset_path: projects/packages/nifty-linux-x64/lib/nifty-linux-x64-gnu.node
          - os: windows-latest
            asset_name: nifty-win32-x64-msvc.node
            asset_path: projects/packages/nifty-win32-x64/lib/nifty-win32-x64-msvc.node
          - os: macos-latest
            asset_name: nifty-darwin-arm64.node
            asset_path: projects/packages/nifty-darwin-arm64/lib/nifty-darwin-arm64.node

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Build Node-API addon
        run: npm run build:napi
      - name: Upload native addon to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_path }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref_name }}
